
services:
  db:
    image: mysql:8.0
    container_name: bsp_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: he753951       # root 密碼
      MYSQL_DATABASE: Backend_side_project # 自動建立的資料庫
      MYSQL_USER: appuser                  # 專用使用者
      MYSQL_PASSWORD: apppass123           # 使用者密碼
    volumes:
      - db_data:/var/lib/mysql
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro  # 初始化 schema
    ports:
      - "3307:3306"                       # 本機 3307 對應容器 3306

  backend:
    build: .
    container_name: bsp_backend
    restart: on-failure
    depends_on:
      - db
    environment:
      DB_URL:   jdbc:mysql://db:3306/Backend_side_project?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      DB_USER:  appuser
      DB_PASS:  apppass123
      SERVER_PORT: 8080
    ports:
      - "8081:8080"                       # 本機 8081 對應容器 8080

volumes:
  db_data: {}