info:
  title: New Collection
  version: 1.0.0
openapi: 3.0.0
servers:
  - url: http://localhost:8080
    description: 本地開發伺服器
paths:
  /cart:
    post:
      requestBody:
        content:
          application/json:
            example:
              member_id: 50717
              product_id: 25
              quantity: 2
      responses:
        '200':
          description: Successful response
      summary: '{{base_url}}cart(商品正確加入購物車)'
    put:
      requestBody:
        content:
          application/json:
            example:
              member_id: 50690
              product_id: 6
              quantity: 3
      responses:
        '200':
          description: Successful response
      summary: '{{base_url}}/cart(更新購物車商品數量)'
  /cart?member_id=50717&product_id=25:
    delete:
      responses:
        '200':
          description: Successful response
      summary: '{{base_url}}/cart?member_id=50717&product_id=25(移除購物車商品)'
  /cart?member_id=50690:
    get:
      responses:
        '200':
          description: Successful response
      summary: '{{base_url}}/cart?member_id=50690(依會員編號查看購物車)'
  /member:
    post:
      requestBody:
        content:
          application/json:
            example:
              address: Taidoeei
              create_at: '2025-04-26T12:00:00'
              email: testuser@du8mple.com
              name: testUssss
              password: pass666
              phone: 091200999
      responses:
        '200':
          description: Successful response
      summary: '{{base_url}}/member(註冊會員)'
  /member/login:
    post:
      requestBody:
        content:
          application/json:
            example:
              email: testuser@du8mple.com
              password: pass666
      responses:
        '200':
          description: Successful response
      summary: '{{base_url}}member/login(會員登入)'
  /order:
    post:
      requestBody:
        content:
          application/json:
            example:
              member_id: 50710
      responses:
        '200':
          description: Successful response
      summary: '{{base_url}}/order'
  /product:
    get:
      responses:
        '200':
          description: Successful response
      summary: '{{base_url}}product(瀏覽商品列表)'
  /user/categories:
    delete:
      requestBody:
        content:
          application/json:
            example:
             category_id: 18
      responses:
        '200':
          description: Successful response
      summary: '{{base_url}}/user/categories'
    get:
      responses:
        '200':
          description: Successful response
      summary: '{{base_url}}/user/categories'
    post:
      requestBody:
        content:
          application/json:
            example:
              name: blabla
      responses:
        '200':
          description: Successful response
      summary: '{{base_url}}/user/categories'
    put:
      requestBody:
        content:
          application/json:
            example:
              category_id: 23
              name: TestCat_31861_upd
      responses:
        '200':
          description: Successful response
      summary: '{{base_url}}/user/categories'
  /user/members:
    delete:
      requestBody:
        content:
          application/json:
            example:
              member_id: 50726
      responses:
        '200':
          description: Successful response
      summary: '{{base_url}}/user/members'
    get:
      responses:
        '200':
          description: Successful response
      summary: '{{base_url}}/member(會員列表)'
    post:
      requestBody:
        content:
          application/json:
            example:
              name: 今晚打老虎
              password: 0518
              phone: 5018
              address: 5018
              email: 5018
      responses:
        '200':
          description: Successful response
      summary: '{{base_url}}/user/members'
    put:
      requestBody:
        content:
          application/json:
            example:
              name: 小王_udp
              password: 333
              phone: 5
              address: 5
              email: 6
              member_id: 333
      responses:
        '200':
          description: Successful response
      summary: '{{base_url}}/user/members'
  /user/members?member_id=111:
    get:
      responses:
        '200':
          description: Successful response
      summary: '{{base_url}}/user/members'
  /user/orders?member_id=30678:
    get:
      responses:
        '200':
          description: Successful response
      summary: '{{base_url}}/user/orders'
  /user/products:
    delete:
      requestBody:
        content:
          application/json:
            example:
              product_id: 37
      responses:
        '200':
          description: Successful response
      summary: '{{base_url}}/user/products'
    get:
      responses:
        '200':
          description: Successful response
      summary: '{{base_url}}/user/products'
    post:
      requestBody:
        content:
          application/json:
            example:
              name: 超屌手機
              price: 987
              soh: 567
              category_id: 11
      responses:
        '200':
          description: Successful response
      summary: '{{base_url}}/user/products'
    put:
      requestBody:
        content:
          application/json:
            example:
              name: 超屌電視_
              price: 966
              soh: 5
              category_id: 11
              is_active: true
              product_id: 45
      responses:
        '200':
          description: Successful response
      summary: '{{base_url}}/user/products'
